Issue 17
chatbus/chatbus_hompage pull request #25
Opened 2022-09-21 14:14 UTC by CheonInJeong

1. 멤버 데이터 분리
- donny.mdx를 못찾아요.😱
2. faqCard 컴포넌트 생성하여 분리
- @thgml21004 분리하면서 좌우로 faq를 나누던 아래 태그를 쓸 수가 없어서 faq가 한쪽으로만 나와요😭
- `<div className="w-full px-4 lg:w-1/2">`
3. index 페이지 데이터 분리
- markdown 문법이 적용이 안돼요😢

2022-09-22 00:17 UTC, jams777 commented
이거 하는김에 예제소스인 블로그 폴더 관련된것도 삭제할 수 있을까요? ㅎ

2022-09-22 10:12 UTC, jams777 commented
> 
markdown 문법이 적용이 안돼요
이부분은 mdx 로 오면서 바뀐건데요. 다른 플러그인 셋팅을 통해서 조금 더 멋진 markdown 을 만들면 될듯하니
이번엔 그냥 가고 다음 이슈로 하시죠~ ^^

2022-09-23 00:17 UTC, jams777 requested changes
이걸 눌러야 보이나요

2022-09-23 00:17 UTC, jams777 commented on data/member/chenchen.mdx
> +hero_image_alt: "프로필 사진"
hero_image_alt 가 키로 들어가는지 빌드에서 에러가 나네요.
빌드 에러는 '첸첸프로필 사진'으로 바꾸면 해결될듯합니다.

2022-09-23 00:17 UTC, jams777 commented on data/member/donny.mdx
> +hero_image_alt: "프로필 사진"
hero_image_alt 가 키로 들어가는지 빌드에서 에러가 나네요.
빌드 에러는 '도니프로필 사진'으로 바꾸면 해결될듯합니다.

2022-09-23 00:17 UTC, jams777 commented on data/member/ella.mdx
> +hero_image_alt: "프로필 사진"
hero_image_alt 가 키로 들어가는지 빌드에서 에러가 나네요.
빌드 에러는 '엘라프로필 사진'으로 바꾸면 해결될듯합니다.

2022-09-23 00:17 UTC, jams777 commented on data/member/usopp.mdx
> +---
지금 당장은 우솝이 하기 어렵다고 해서 멤버에서 잠깐 빠졌어요.
데이터 중에 상태를 관리하는 부분이 있으면 안보여주면 좋을 듯해요~

2022-09-23 00:17 UTC, jams777 commented on src/components/memberCard.js
> +            <div className="w-full px-4 sm:w-1/2 lg:w-1/4" key={member.id}>
멤버 아이디는 따로 관리하는건가요???
아니면 그냥 map 의 인덱스로 해도 ^^

2022-09-23 00:17 UTC, jams777 commented on data/member/donny.mdx
> +hero_image:"./user-donny.jpg"
키 값 뒤에 한칸이 안떨어져서 워닝이 있어요

2022-09-23 00:17 UTC, jams777 commented on src/pages/index.js
> +    const title = data.mdx.frontmatter.title;
frontmatter 가 없다는데요~
config 폴더에 mdx 를 member 만 데이터로 만들게 되어 있는거 같아요

2022-09-23 00:17 UTC, jams777 commented on src/pages/index.js
> +    const excerpt = data.mdx.excerpt;
config 폴더에 mdx 를 member 만 데이터로 만들게 되어 있는거 같아요

2022-09-23 00:17 UTC, jams777 commented on gatsby-config.js
> +    {
member 외에 다른것들도 데이터로 뽑아놔야 그래프큐엘에서 가져다 사용할 수 있을 것 같아요

2022-09-23 00:38 UTC, thgml21004 requested changes

2022-09-23 00:38 UTC, thgml21004 commented on src/pages/faq.js
> +  return <Layout pageTitle="FAQ">
Layout을 제거하시면 됩니다~

2022-09-23 00:48 UTC, thgml21004 commented on gatsby-config.js
> +    {
챈챈님 faq 빠졌어요

    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: `faq`,
        path: `${__dirname}/data/faq`,
      },
    },

2022-09-23 09:53 UTC, jams777 commented
이후에 변경된 소스가 많아서 conflicts 가 나네요~ 잘 머지까지 부탁드려요 ^^

2022-09-26 23:22 UTC, jams777 commented on data/member/donny.mdx
> +hero_image:"./user-donny.jpg"
오~~ 됩니다.

2022-09-26 23:23 UTC, jams777 commented on data/member/donny.mdx
> +hero_image_alt: "프로필 사진"
이건 같아도 에러는 안나네요 ^^

2022-09-26 23:23 UTC, jams777 commented on data/member/ella.mdx
> +hero_image_alt: "프로필 사진"
이건 같아도 에러는 안나네요 ^^

2022-09-26 23:24 UTC, jams777 commented on data/member/usopp.mdx
> +---
이건 같아도 에러는 안나네요 ^^

2022-09-26 23:24 UTC, jams777 commented on gatsby-config.js
> +    {
faq 데이터 잘 들어오네요~

2022-09-26 23:25 UTC, jams777 commented on src/components/memberCard.js
> +            <div className="w-full px-4 sm:w-1/2 lg:w-1/4" key={member.id}>
키값 관리는 나중에 해보는게 좋을 듯합니다. ^^

2022-09-26 23:31 UTC, jams777 commented on src/pages/faq.js
> +  return <Layout pageTitle="FAQ">
잘 빠졌습니다.~

2022-09-26 23:31 UTC, jams777 approved these changes
잘 변경된거 같아요~

2022-09-27 00:36 UTC, merged